// Embers of Vaelthorne — fictional campaign data for the demo.
// All names, places, and lore are original.

window.CAMPAIGN = {
  name: "Embers of Vaelthorne",
  subtitle: "A kingdom mourns. An ember waits.",
  session: 14,
  sessionsTotal: 28,
  nextSession: "Sat, 27 Vael · 19:00",
  party: [
    { name: "Aelric Vorn", role: "Half-elf Warlock", patron: "The Hollow Sovereign", hp: "38/52", note: "owes a debt to the Veiled Hand" },
    { name: "Marda Stonebrew", role: "Dwarven Cleric", patron: "Order of the Pale Moon", hp: "61/61", note: "carries her brother's signet" },
    { name: "Sable", role: "Tiefling Rogue", patron: "—", hp: "34/41", note: "knows about the ledger" },
    { name: "Yew of the Quiet", role: "Wood-elf Ranger", patron: "—", hp: "47/47", note: "tracking the white stag" },
  ],
  location: {
    name: "Ashen Hollow",
    region: "The Margreave",
    note: "A flooded mining village, lantern-lit at noon. Smell of wet iron.",
  },
  lastSession: {
    title: "Session XIII · The Drowned Lantern",
    bullets: [
      "Party recovered the half-burned ledger from Ferren's study.",
      "Lady Halsane recognised Marda's signet — refused to speak further.",
      "Sable lifted a wax-sealed letter bearing the Crown of Asters.",
      "A child in the market sang the regicide rhyme; no one stopped her.",
      "Yew saw the white stag west of the Hollow. It bled silver.",
    ],
  },
  prep: [
    { kind: "scene", title: "Cold open: the funeral procession", note: "Bells out of tune. The widow does not weep." },
    { kind: "scene", title: "The Veiled Hand makes contact", note: "Through Aelric's dreams or the innkeep — DM's choice." },
    { kind: "beat", title: "Reveal: the ledger names a Pale Moon abbot", note: "Land this if the party reads page 6." },
    { kind: "beat", title: "Faction tick: Iron Concord moves on Greymarch", note: "If session runs long, defer to next." },
  ],
  quickRolls: [
    { label: "Perception (avg)", v: "+5" },
    { label: "Insight (avg)",     v: "+4" },
    { label: "Stealth (best)",    v: "+8" },
    { label: "Arcana (best)",     v: "+7" },
  ],
};

window.FACTIONS = [
  {
    id: "iron-concord",
    name: "The Iron Concord",
    sigil: "concord",
    ideology: "Order through steel. The crown is a contract.",
    leader: "High Marshal Caedren Vask",
    seat: "Greymarch Citadel",
    disposition: "hostile",
    clock: { segments: 8, filled: 5, label: "March on Greymarch" },
    color: "iron",
    summary: "Standing army loyal first to the office of the crown, not its wearer. They have not yet decided whether Vaelthorne still has a crown.",
  },
  {
    id: "veiled-hand",
    name: "The Veiled Hand",
    sigil: "hand",
    ideology: "What is hidden is sovereign.",
    leader: "Unknown · the Quiet Chair",
    seat: "The Sable Library, beneath Ashen Hollow",
    disposition: "ambiguous",
    clock: { segments: 6, filled: 4, label: "Recover the Ledger" },
    color: "oxblood",
    summary: "A library of secrets older than the kingdom. They sold the regicide. They will sell the next one.",
  },
  {
    id: "pale-moon",
    name: "Order of the Pale Moon",
    sigil: "moon",
    ideology: "Mercy is a discipline. Forgiveness is a vow.",
    leader: "Abbess Halsane Mire",
    seat: "Cloister of the Drowned Lantern",
    disposition: "ally",
    clock: { segments: 6, filled: 2, label: "Sanctuary for the Heir" },
    color: "moon",
    summary: "Healers and chroniclers. Their abbey hides the only living witness to the king's death.",
  },
  {
    id: "ashen-court",
    name: "The Ashen Court",
    sigil: "crown",
    ideology: "The throne is a flame. Tend it or be consumed.",
    leader: "Regent Theron Vael",
    seat: "Cinderhold",
    disposition: "neutral",
    clock: { segments: 4, filled: 1, label: "Coronation of a Pretender" },
    color: "ember",
    summary: "What remains of the royal house. A regent who governs an empty chair, and a court that performs grief for an audience that has stopped watching.",
  },
  {
    id: "saltbrothers",
    name: "The Saltbrothers",
    sigil: "anchor",
    ideology: "Salt forgives. Salt remembers.",
    leader: "Anchor-Captain Ren Holloway",
    seat: "Tidefast",
    disposition: "neutral",
    clock: { segments: 6, filled: 3, label: "Blockade of the Margreave" },
    color: "forest",
    summary: "A guild of smugglers and salt-priests. The fastest road north runs through their hulls and their loyalties.",
  },
];

window.NPCS = [
  {
    id: "halsane",
    name: "Abbess Halsane Mire",
    title: "Mother of the Drowned Lantern",
    faction: "pale-moon",
    disposition: "ally",
    location: "Ashen Hollow · Cloister",
    appearance: "Sixty. Skin like vellum. Right hand permanently inked from chronicling.",
    voice: "Low, measured. Pauses before nouns.",
    wants: "To keep the witness alive and quiet.",
    fears: "That the witness is also the rightful heir.",
    secrets: ["She knows where the heir sleeps.", "She baptised the regent in his cradle."],
    bonds: ["Marda Stonebrew — knew her brother."],
    note: "If pressed about the ledger, she will offer the rosary instead. Let her.",
    quote: "Mercy is the slowest blade. It cuts last.",
    likely: true,
    tags: ["cleric", "chronicler", "ally"],
  },
  {
    id: "caedren",
    name: "High Marshal Caedren Vask",
    title: "Bearer of the Iron Writ",
    faction: "iron-concord",
    disposition: "hostile",
    location: "Greymarch Citadel",
    appearance: "Tall. Half-grey. A scar that runs through the lip and the title.",
    voice: "Quiet. Names everyone by rank, never name.",
    wants: "A king he can salute.",
    fears: "That the office has outlived the crown.",
    secrets: ["He carried the king's body from the field.", "He has not slept since."],
    bonds: ["Theron Vael — owes him a kindness he cannot repay."],
    note: "Refuses parley unless the party surrenders their colors first.",
    quote: "The crown is a contract. I am its signature.",
    likely: true,
    tags: ["soldier", "lawman", "hostile"],
  },
  {
    id: "ferren",
    name: "Ferren of the Ledger",
    title: "Clerk, Veiled Hand",
    faction: "veiled-hand",
    disposition: "ambiguous",
    location: "deceased — Ashen Hollow",
    appearance: "Slight. Ink on every fingerpad. A coat too heavy for him.",
    voice: "—",
    wants: "—",
    fears: "—",
    secrets: ["The ledger is a copy. The original is in Tidefast.", "Ferren is not dead."],
    bonds: ["Sable — passed her a key in the market, three sessions ago."],
    note: "If the party returns to his study, the body is gone.",
    quote: "I write what the world is too embarrassed to remember.",
    likely: false,
    tags: ["clerk", "deceased?", "mystery"],
  },
  {
    id: "theron",
    name: "Regent Theron Vael",
    title: "Regent of the Ashen Court",
    faction: "ashen-court",
    disposition: "ambiguous",
    location: "Cinderhold",
    appearance: "Forty. Beautiful in the way a mask is beautiful.",
    voice: "Warm. Public. Practiced.",
    wants: "To be remembered as the one who held the line.",
    fears: "That his brother's child is still breathing somewhere.",
    secrets: ["He commissioned the regicide.", "He does not remember why anymore."],
    bonds: ["Caedren Vask — boyhood friend."],
    note: "Will receive the party in audience. Will not be alone with them.",
    quote: "Grief is a long, public office.",
    likely: true,
    tags: ["noble", "regent", "antagonist"],
  },
  {
    id: "renholloway",
    name: "Anchor-Captain Ren Holloway",
    title: "Of the Saltbrothers",
    faction: "saltbrothers",
    disposition: "neutral",
    location: "Tidefast",
    appearance: "A woman built like a winch. Salt in the creases.",
    voice: "Loud, but only when she means it.",
    wants: "The blockade lifted before winter.",
    fears: "That her crew will hang for what she said yes to.",
    secrets: ["She moved the original ledger.", "She loved Ferren. He knew."],
    bonds: ["Ferren — owed him a passage."],
    note: "Will bargain. Will not be threatened.",
    quote: "Salt forgives. I don't.",
    likely: false,
    tags: ["captain", "smuggler", "ally?"],
  },
  {
    id: "child",
    name: "The Hollow Child",
    title: "Witness · Cloister of the Drowned Lantern",
    faction: "pale-moon",
    disposition: "ally",
    location: "Ashen Hollow · Cloister, lower cells",
    appearance: "Eleven. Eyes the wrong color for the hour.",
    voice: "Sings before she speaks.",
    wants: "To go home.",
    fears: "The man with the warm voice.",
    secrets: ["She is the heir.", "She saw the regent in the gardens that night."],
    bonds: ["Halsane Mire — her keeper."],
    note: "If the party meets her, she will sing the regicide rhyme. Halsane will not stop her.",
    quote: "He smiled at the roses and then they were red.",
    likely: false,
    tags: ["child", "witness", "heir"],
  },
];

window.SECRETS = [
  { id: "s1", title: "The Regent ordered the regicide.", weight: "Campaign", status: "sealed", revealsTo: "When the ledger is read in full.", relates: ["theron", "ferren"], onReveal: "Iron Concord clock advances 2. Pale Moon clock advances 1." },
  { id: "s2", title: "The Hollow Child is the rightful heir.", weight: "Campaign", status: "sealed", revealsTo: "When Halsane is given no other choice.", relates: ["child", "halsane"], onReveal: "Ashen Court clock fills. Veiled Hand turns hostile." },
  { id: "s3", title: "Ferren is alive in Tidefast.", weight: "Arc", status: "sealed", revealsTo: "When the body is found missing.", relates: ["ferren", "renholloway"], onReveal: "Saltbrothers disposition shifts to ambiguous." },
  { id: "s4", title: "The Veiled Hand sold the regicide twice.", weight: "Arc", status: "cracked", revealsTo: "Hinted in the ledger margins.", relates: ["veiled-hand"], onReveal: "The second buyer is named in s7." },
  { id: "s5", title: "Caedren carried the body from the field.", weight: "Scene", status: "revealed", revealsTo: "Marda's brother told her, in confidence.", relates: ["caedren"], onReveal: "Already revealed in Session XI." },
  { id: "s6", title: "Aelric's patron is the King's ghost.", weight: "Campaign", status: "sealed", revealsTo: "When Aelric uses the pact in the throne room.", relates: ["aelric"], onReveal: "Aelric gains a new invocation. Loses two memories." },
  { id: "s7", title: "The second buyer was the Pale Moon.", weight: "Arc", status: "sealed", revealsTo: "Crack s4 first. Then read page 11.", relates: ["pale-moon", "veiled-hand"], onReveal: "Pale Moon disposition becomes ambiguous." },
  { id: "s8", title: "The white stag bleeds where a king has lied.", weight: "Lore", status: "cracked", revealsTo: "Yew already knows. The party does not.", relates: ["yew"], onReveal: "Useful for divinations in the Margreave." },
];

window.TIMELINE = [
  { era: "Before", marker: "—II", title: "The Concordat of Asters", note: "Five houses sign. Vaelthorne is named." },
  { era: "Before", marker: "—I",  title: "The Pale Plague", note: "Two houses fall. The Pale Moon takes the orphans." },
  { era: "Reign",  marker: "I",   title: "Coronation of Edrick Vael", note: "The last uncontested crown." },
  { era: "Reign",  marker: "II",  title: "The Margreave Floods", note: "Three winters of rain. The salt roads close." },
  { era: "Reign",  marker: "III", title: "Birth of the Hollow Child", note: "Kept from the court. Sent to the cloister.", flagged: true },
  { era: "Reign",  marker: "IV",  title: "Regicide at the Garden of Asters", note: "Edrick dies between two roses. No witnesses — officially.", flagged: true },
  { era: "Embers", marker: "V",   title: "The Regency of Theron Vael", note: "An empty chair, attended." },
  { era: "Embers", marker: "VI",  title: "The Iron Writ is read aloud at Greymarch", note: "The army does not march. Yet." },
  { era: "Embers", marker: "VII", title: "Party arrives in Ashen Hollow", note: "Session I.", flagged: true, party: true },
  { era: "Embers", marker: "VIII",title: "The Drowned Lantern", note: "Session XIII. The ledger surfaces.", flagged: true, party: true },
  { era: "Now",    marker: "IX",  title: "Funeral procession at Cinderhold", note: "Scheduled for Session XIV.", upcoming: true },
  { era: "Soon",   marker: "X",   title: "March on Greymarch", note: "Iron Concord clock at 5/8.", upcoming: true, faction: "iron-concord" },
  { era: "Soon",   marker: "XI",  title: "Blockade of the Margreave tightens", note: "Saltbrothers clock at 3/6.", upcoming: true, faction: "saltbrothers" },
];

window.RELATIONSHIPS = {
  nodes: [
    { id: "theron",     label: "Theron Vael",       kind: "noble",   x: 0.50, y: 0.22, ring: "court" },
    { id: "caedren",    label: "Caedren Vask",      kind: "soldier", x: 0.82, y: 0.36, ring: "iron" },
    { id: "halsane",    label: "Halsane Mire",      kind: "cleric",  x: 0.22, y: 0.42, ring: "moon" },
    { id: "child",      label: "Hollow Child",      kind: "witness", x: 0.30, y: 0.66, ring: "moon" },
    { id: "ferren",     label: "Ferren",            kind: "clerk",   x: 0.55, y: 0.58, ring: "hand" },
    { id: "renholloway",label: "Ren Holloway",      kind: "captain", x: 0.78, y: 0.70, ring: "salt" },
    { id: "marda",      label: "Marda",             kind: "party",   x: 0.10, y: 0.78, ring: "party" },
    { id: "sable",      label: "Sable",             kind: "party",   x: 0.42, y: 0.84, ring: "party" },
    { id: "aelric",     label: "Aelric",            kind: "party",   x: 0.66, y: 0.86, ring: "party" },
    { id: "yew",        label: "Yew",               kind: "party",   x: 0.90, y: 0.88, ring: "party" },
    { id: "edrick",     label: "Edrick Vael †",     kind: "ghost",   x: 0.50, y: 0.06, ring: "ghost" },
  ],
  edges: [
    { a: "theron",     b: "edrick",     rel: "blood",    label: "brother" },
    { a: "theron",     b: "caedren",    rel: "ally",     label: "boyhood" },
    { a: "theron",     b: "ferren",     rel: "enmity",   label: "commissioned", secret: true },
    { a: "halsane",    b: "child",      rel: "ward",     label: "keeper" },
    { a: "halsane",    b: "marda",      rel: "blood",    label: "brother lost" },
    { a: "ferren",     b: "renholloway",rel: "love",     label: "promised" },
    { a: "ferren",     b: "sable",      rel: "debt",     label: "passed a key" },
    { a: "caedren",    b: "edrick",     rel: "loyal",    label: "carried him" },
    { a: "aelric",     b: "edrick",     rel: "pact",     label: "patron", secret: true },
    { a: "yew",        b: "child",      rel: "knows",    label: "the stag" },
    { a: "renholloway",b: "ferren",     rel: "love",     label: "—" },
    { a: "child",      b: "theron",     rel: "enmity",   label: "witnessed", secret: true },
  ],
};

window.MAP_LOCATIONS = [
  { id: "cinderhold",   label: "Cinderhold",          x: 0.52, y: 0.20, kind: "capital",  note: "The empty throne. Regent in residence." },
  { id: "greymarch",    label: "Greymarch Citadel",   x: 0.80, y: 0.34, kind: "fortress", note: "Iron Concord stronghold." },
  { id: "ashen-hollow", label: "Ashen Hollow",        x: 0.36, y: 0.52, kind: "town",     note: "Party here. Flooded mines.", party: true },
  { id: "cloister",     label: "Drowned Lantern",     x: 0.30, y: 0.60, kind: "abbey",    note: "Pale Moon cloister. The witness sleeps below." },
  { id: "tidefast",     label: "Tidefast",            x: 0.72, y: 0.74, kind: "port",     note: "Saltbrothers. The original ledger." },
  { id: "garden",       label: "Garden of Asters",    x: 0.58, y: 0.10, kind: "ruin",     note: "Where the king died.", flagged: true },
  { id: "stag",         label: "The Bleeding Stag",   x: 0.18, y: 0.34, kind: "omen",     note: "Yew saw it here, twice." },
  { id: "library",      label: "Sable Library",       x: 0.40, y: 0.46, kind: "hidden",   note: "Beneath Ashen Hollow. Veiled Hand seat.", hidden: true },
  { id: "blockade",     label: "Salt Blockade",       x: 0.86, y: 0.62, kind: "danger",   note: "Three hulls. Six guns. One captain." },
];

window.QUESTS = [
  { id: "q1", title: "The Half-Burned Ledger",       arc: "Main",     state: "active",  step: 3, total: 5, next: "Read page 6 aloud at the cloister.", giver: "Ferren (posthumous)", stakes: "Names every buyer in the regicide. Changes the war." },
  { id: "q2", title: "A Witness Below the Lantern",  arc: "Main",     state: "active",  step: 1, total: 4, next: "Earn Halsane's audience.",           giver: "The party",           stakes: "The Hollow Child is the last living witness. If she dies, the truth dies." },
  { id: "q3", title: "The White Stag",               arc: "Side",     state: "active",  step: 2, total: 3, next: "Follow the silver trail west.",       giver: "Yew of the Quiet",    stakes: "An omen the Margreave has not shown in twenty years." },
  { id: "q4", title: "Aelric's Patron",              arc: "Personal", state: "dormant", step: 0, total: 3, next: "Triggered by use in the throne room.", giver: "Aelric Vorn",        stakes: "A debt to a dead king. Or something wearing his face." },
];

// ── Rumors on the wind — for the War Room "living world" card ──────────
window.RUMORS = [
  { id: "r1", text: "A bell tolled at Cinderhold at the wrong hour. The bellmaster has not been seen since.", source: "innkeep at the Drowned Lantern", weight: "common", relates: ["theron"] },
  { id: "r2", text: "Iron Concord scouts ride the Margreave road in pairs now, never alone. They count the wagons.", source: "salt-pedlar from Tidefast", weight: "tactical", relates: ["caedren", "iron-concord"] },
  { id: "r3", text: "A child sings the regicide rhyme in three markets. No one remembers teaching it.", source: "Yew, second watch", weight: "ominous", relates: ["child"] },
  { id: "r4", text: "The white stag was seen drinking from the Aster fountain. It bled silver into the water.", source: "a Pale Moon novice", weight: "lore", relates: ["yew"] },
  { id: "r5", text: "A man in Ferren's coat bought passage at Tidefast. The captain refused him twice and accepted on the third.", source: "Saltbrother gossip", weight: "secret", relates: ["ferren", "renholloway"] },
  { id: "r6", text: "Halsane has not lit the Lantern these three nights. The cloister says she is in prayer.", source: "a smith's apprentice", weight: "ominous", relates: ["halsane"] },
];

// ── Religions / orders / beliefs — for World Codex ─────────────────────
window.RELIGIONS = [
  { id: "rel-pale-moon", name: "The Pale Moon",        kind: "monastic order",   sigil: "moon",   tenets: "Mercy is a discipline. Memory is a sacrament. Forgiveness is the slowest vow." },
  { id: "rel-asters",    name: "The Five Asters",      kind: "civic cult",       sigil: "crown",  tenets: "One bloom for each founding house. They wilt in lockstep." },
  { id: "rel-hollow",    name: "The Hollow Sovereign", kind: "forbidden patron", sigil: "concord",tenets: "The throne dreams. The dreamer is the throne. The throne is empty." },
  { id: "rel-salt",      name: "The Salt Brotherhood", kind: "guild-faith",      sigil: "anchor", tenets: "Salt forgives. Salt remembers. Salt does not lie about the sea." },
];

// ── Relics / items of note ─────────────────────────────────────────────
window.RELICS = [
  { id: "rel-ledger",   name: "The Half-Burned Ledger",       kind: "tome",       category: "relic", desc: "Names every secret the Veiled Hand sold this century. Burned at one corner. Cold to the touch." },
  { id: "rel-signet",   name: "Marda's Brother's Signet",     kind: "ring",       category: "relic", desc: "Iron and salt. Cannot be removed once worn. Recognizes its kin." },
  { id: "rel-aster",    name: "Aster of the Garden",          kind: "flower",     category: "relic", desc: "Plucked the night Edrick died. Still bleeds silver in moonlight." },
  { id: "rel-lantern",  name: "The Drowned Lantern",          kind: "relic",      category: "relic", desc: "A lantern that burns underwater. Lit only when the Abbess has a witness to keep." },
  { id: "rel-writ",     name: "The Iron Writ",                kind: "document",   category: "item",  desc: "The Iron Concord's standing order to march. Sealed with three brass clasps. Two remain." },
  { id: "rel-key",      name: "Ferren's Key",                 kind: "key",        category: "item",  desc: "Opens nothing in Ashen Hollow. Opens a door at the bottom of Tidefast harbour." },
  { id: "rel-crown",    name: "The Hollow Crown",             kind: "crown",      category: "relic", desc: "The last crown of Vaelthorne. Kept in the Regent's vault. Slightly too large for any living head." },
  { id: "rel-vial",     name: "Pale Moon Vial",               kind: "consumable", category: "item",  desc: "A glass vial of Abbess Halsane's making. Warm to the touch. Drinking it lets you remember one thing you forgot on purpose." },
  { id: "rel-anchor",   name: "Saltbrother Anchor-Token",     kind: "token",      category: "item",  desc: "Pressed copper, stamped with a drowned anchor. Gets you aboard any Saltbrother vessel, once." },
  { id: "rel-cloak",    name: "The Veil Cloak",               kind: "armor",      category: "relic", desc: "Veiled Hand issue. Doesn't make you invisible — makes people unsure they saw you." },
  { id: "rel-dagger",   name: "Caedren's Field Dagger",       kind: "weapon",     category: "item",  desc: "Standard Iron Concord issue, except for the initials scratched into the pommel. EC — Edrick's mark." },
  { id: "rel-coin",     name: "Silver Coin of the Old Realm", kind: "coin",       category: "relic", desc: "Minted two centuries ago. Worth nothing to merchants. Worth everything to the right collector." },
];

// ── Lore / chronicles — historical articles ────────────────────────────
window.LORE = [
  { id: "lore-concordat", name: "The Concordat of Asters",    kind: "history",  desc: "The five-house treaty that founded Vaelthorne, signed in the Garden two centuries ago. Two of its signatory houses are now extinct." },
  { id: "lore-plague",    name: "The Pale Plague",            kind: "history",  desc: "The fever that took the second and fourth houses. The Pale Moon raised their orphans, including the Abbess and the High Marshal." },
  { id: "lore-rhyme",     name: "The Regicide Rhyme",         kind: "song",     desc: "A children's rhyme: two roses, a vow, the third one knew. No author. Spreads like a fever. Sung in markets within a day of the king's death." },
  { id: "lore-stag",      name: "The Bleeding Stag",          kind: "myth",     desc: "The Margreave's omen. Bleeds silver where a crowned head has lied. Last seen the week the regency was declared." },
  { id: "lore-veil",      name: "On the Veiled Hand",         kind: "treatise", desc: "A clerk's library that sells what is hidden. Older than the kingdom. Their ledgers are the second draft of the chronicle." },
];

// ── Encounters — staged tactical scenes ───────────────────────────────────
window.ENCOUNTERS = [
  {
    id: "enc-1",
    title: "Iron Concord Roadblock",
    location: "North Road, the Margreave",
    threat: "medium",
    status: "planned",
    notes: "Sergeant Orvak has the party's description. Detain, not kill — unless provoked. He'll send a rider if the party flees.",
    enemies: [
      { id: "e1a", name: "Iron Soldier", count: 3, hp: 11, maxHp: 11, ac: 16, note: "Spear and shield. Follow orders." },
      { id: "e1b", name: "Sergeant Orvak", count: 1, hp: 26, maxHp: 26, ac: 17, note: "Knows Caedren personally. Will not be bribed." },
    ],
  },
  {
    id: "enc-2",
    title: "The Hollow Beast",
    location: "Ashen Hollow · the flooded mine",
    threat: "deadly",
    status: "planned",
    notes: "Drawn by the silver stag. Immune to fire. Advantage on attack rolls in moonlight. Retreats if the Hollow Child sings. Do not run this if the party is already below 50% HP.",
    enemies: [
      { id: "e2a", name: "Hollow Beast", count: 1, hp: 84, maxHp: 84, ac: 14, note: "Tracks blood, not sight. Cannot cross running water." },
    ],
  },
  {
    id: "enc-3",
    title: "Veiled Hand Extraction",
    location: "The Sable Library",
    threat: "high",
    status: "planned",
    notes: "Three agents want the ledger back. No negotiation after round one. If Miren is taken alive, she knows who holds the original.",
    enemies: [
      { id: "e3a", name: "Hand Agent", count: 2, hp: 18, maxHp: 18, ac: 13, note: "Crossbow. Prefers cover. Retreats at half HP." },
      { id: "e3b", name: "Miren (Quiet Blade)", count: 1, hp: 32, maxHp: 32, ac: 15, note: "Paralytic dart — two uses. Knows the party's names." },
    ],
  },
];

// ── Calendar — in-world dates and deadlines ────────────────────────────────
window.CALENDAR = [
  { id: "cal-1", date: "14 Vael",     title: "Session XIV · The Bells of Cinderhold", kind: "session",  notes: "Funeral procession. The widow counts the crowd twice." },
  { id: "cal-2", date: "21 Vael",     title: "Iron Concord Deadline",                  kind: "deadline", notes: "Vask's proclamation expires. If no crown is named, the march begins." },
  { id: "cal-3", date: "28 Vael",     title: "Session XV (planned)",                   kind: "session",  notes: "Tentative — Cinderhold or Tidefast depending on party path." },
  { id: "cal-4", date: "1 Highwane",  title: "Pale Moon Vigil",                        kind: "omen",     notes: "Halsane fasts three days before the Pale Moon crests. She speaks truths — only the ones she chooses." },
  { id: "cal-5", date: "8 Highwane",  title: "The Ashen Market",                       kind: "world",    notes: "Traders from Tidefast arrive. Good cover for a passage north. Saltbrothers will be watching." },
  { id: "cal-6", date: "15 Highwane", title: "Saltbrothers Blockade Review",           kind: "deadline", notes: "Holloway's deadline. If the Concord hasn't moved, she releases the salt roads — and the north." },
];

// ── Handouts — player-facing documents ────────────────────────────────────
window.HANDOUTS = [
  {
    id: "handout-1",
    title: "The Burned Ledger — Page 6",
    kind: "document",
    body: "...by order of the Regent's office, the sum of four hundred crowns transferred to an agent of the Veiled Hand, for services rendered on the fourteenth night of Embers.\n\nThe name of the king is not written here. It did not need to be.\n\n[The remainder of the page is ash.]",
    public: false,
  },
  {
    id: "handout-2",
    title: "Wax-Sealed Letter · Crown of Asters",
    kind: "letter",
    body: "To the one who carries the rose signet —\n\nIf you are reading this, Ferren is dead or wishes to be. Do not look for him in Ashen Hollow.\n\nThe child must not reach Cinderhold before the seventh bell. You know what to do if she does.\n\nBurn this.\n\n— T.V.",
    public: false,
  },
  {
    id: "handout-3",
    title: "The Iron Writ — Public Proclamation",
    kind: "document",
    body: "BY ORDER OF THE IRON CONCORD, ACTING IN THE INTEREST OF THE REALM:\n\nIn the absence of a crowned sovereign, the Concord assumes interim authority over the Margreave road, the Salt Blockade, and all garrison posts between Cinderhold and Greymarch Citadel.\n\nAny party found obstructing Concord patrols shall be held at the nearest garrison without trial for a period not to exceed thirty days.\n\nThis writ expires at the first crowning, or at the end of the month of Vael — whichever comes first.\n\nSigned: High Marshal Caedren Vask\nSealed: The Iron Concord, Third Seal",
    public: true,
  },
  {
    id: "handout-4",
    title: "Marda's Brother's Last Note",
    kind: "note",
    body: "Marda —\n\nI can't tell you where I'm going. If you find the signet on someone else's hand, that's how you'll know.\n\nI'm sorry about the dog.\n\nDon't trust the bells.",
    public: false,
  },
  {
    id: "handout-5",
    title: "Intercepted Courier — Salt Road",
    kind: "letter",
    body: "Captain —\n\nThe ledger changed hands at Tidefast. I watched Ren Holloway take it from the body myself. She sealed it in an anchor-cloth and had it sent below decks before dawn.\n\nIf the Concord wants it, they'll have to take the whole ship. She knows that.\n\nI'll send word when she moves.\n\n— your man at the harbour",
    public: false,
  },
];

// ── Random Tables — procedural sparks ─────────────────────────────────────
window.TABLES = [
  {
    id: "table-1",
    title: "Vaelthorne Street Rumors",
    die: "d6",
    entries: [
      "The bellmaster was last seen arguing with a veiled woman at the lower gate.",
      "Iron Concord scouts count every wagon on the Margreave road — and remember the faces.",
      "A child sings the regicide rhyme in three markets. No one taught it to her.",
      "The regent has not slept in seven days. His steward changes the candles hourly.",
      "Someone bribed the city watch last month. The watch still don't know who.",
      "The Hollow Beast was seen drinking from the Aster fountain. The water ran silver.",
    ],
    lastRoll: null,
  },
  {
    id: "table-2",
    title: "Scene Complications",
    die: "d6",
    entries: [
      "A witness. They saw everything and are very frightened.",
      "A locked door — sealed from the inside, recently.",
      "The wrong person arrives first.",
      "The item is already gone, taken within the hour.",
      "Two factions want the same thing, right now, in this room.",
      "Someone in the party is recognised — and the one who knows them knows too much.",
    ],
    lastRoll: null,
  },
  {
    id: "table-3",
    title: "NPC Names · Vaelthorne",
    die: "d8",
    entries: [
      "Caedren",
      "Halsin",
      "Orvak",
      "Mira Fell",
      "Teln of the Shore",
      "Sorra the Pale",
      "Wren Ashwood",
      "Fenwick Mull",
    ],
    lastRoll: null,
  },
  {
    id: "table-4",
    title: "Weather · The Margreave",
    die: "d6",
    entries: [
      "Fog off the flooded mines. Visibility: thirty feet.",
      "Iron rain. Cold, steady, relentless.",
      "A false dawn — orange sky, no sun follows.",
      "Windless. The birds have stopped.",
      "Clear and cold. Every sound carries half a mile.",
      "Hail for ten minutes, then nothing.",
    ],
    lastRoll: null,
  },
  {
    id: "table-5",
    title: "NPC First Reaction",
    die: "d6",
    entries: [
      "Hostile. Hand on weapon. Waiting for an excuse.",
      "Suspicious. Answers nothing directly. Watches the door.",
      "Wary but willing. Wants something first.",
      "Neutral. Professional. Will do business.",
      "Eager. Too eager. Has their own agenda.",
      "Frightened. Knows something they shouldn't. Won't say it.",
    ],
    lastRoll: null,
  },
  {
    id: "table-6",
    title: "What's in the Pocket?",
    die: "d8",
    entries: [
      "A coin from a kingdom that no longer exists.",
      "A folded note, unaddressed, in a hand they don't recognise.",
      "A child's drawing of a house with a door and no windows.",
      "Three copper coins and a dried aster blossom.",
      "A key to something. No label.",
      "A small glass vial — empty but warm.",
      "A lock of hair tied with iron thread.",
      "Nothing. The pocket is sewn shut from the inside.",
    ],
    lastRoll: null,
  },
  {
    id: "table-7",
    title: "Overheard at the Drowned Lantern",
    die: "d6",
    entries: [
      "\"She was there the night the king died. She won't say it but she was.\"",
      "\"The Concord boys are counting faces, not wagons. They're looking for someone.\"",
      "\"Halsane hasn't lit the lantern in three nights. Last time she did that, someone died.\"",
      "\"There's a door in the lower cellar that wasn't there a season ago. I checked.\"",
      "\"The stag came through the market last night. Left silver on the stones.\"",
      "\"Ferren's coat was found at the harbour. No body. Coat was dry.\"",
    ],
    lastRoll: null,
  },
];

// ── Inspiration board — DM mood / reference collection ──────────────────
window.INSPO = [
  {
    id: 'inspo-q1',
    type: 'quote',
    body: 'The map is not the territory. The legend is not the land. But both will lie to you in the same ways.',
    attribution: 'DM note, Session II',
    title: '',
    tags: ['mood', 'lore'],
    color: 'shadow',
    createdAt: 1700000001000,
  },
  {
    id: 'inspo-i1',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    title: 'Ashen Hollow — flooded mine atmosphere',
    tags: ['location', 'mood'],
    note: 'Lantern light on black water. Exactly this.',
    createdAt: 1700000002000,
  },
  {
    id: 'inspo-v1',
    type: 'youtube',
    url: 'https://www.youtube.com/watch?v=8Hk5bpzQHSQ',
    title: 'Dark Medieval Ambience — session background',
    tags: ['mood', 'reference'],
    createdAt: 1700000003000,
  },
  {
    id: 'inspo-q2',
    type: 'quote',
    body: 'Grief is a long, public office. The harder work is what you do when no one is watching.',
    attribution: 'Regent Theron Vael — unused dialogue',
    title: '',
    tags: ['character'],
    color: 'crimson',
    createdAt: 1700000004000,
  },
  {
    id: 'inspo-i2',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80',
    title: 'Cinderhold — throne room ref',
    tags: ['location'],
    note: 'Empty throne, dusty light from high windows.',
    createdAt: 1700000005000,
  },
  {
    id: 'inspo-q3',
    type: 'quote',
    body: 'Salt forgives. Salt remembers. Salt does not lie about what it has touched.',
    attribution: 'Saltbrother proverb',
    title: '',
    tags: ['lore'],
    color: 'moon',
    createdAt: 1700000006000,
  },
];
